### ISSUE TITLE
Invalid Charge Id

### ISSUE THREAD

**Issue by carlbinalla** [checkout/checkout-php-library#102]
When I try to use the **Verify Payment Token Charge** codes, I always receive this error:

>An error has occurred while processing your transaction Invalid Charge id

I'm pretty sure I am passing a payment token, and with minimum details for simplicity.

**PaymentTokenAPI**

    use com\checkout;
    class PaymentTokenAPI {
        private $apiClient;
        private $tokenService;
        private $tokenPayload;

        function __construct($secretKey) {
            $this->apiClient = new checkout\ApiClient($secretKey);
            $this->tokenService = $this->apiClient->tokenService();
            $this->tokenPayload = new checkout\ApiServices\Tokens\RequestModels\PaymentTokenCreate();
        }
        public function setInvestmentValue($value) {
            $this->tokenPayload->setCurrency('PHP');
            $this->tokenPayload->setValue("$value");
        }
        public function createPaymentToken() {
            $paymentToken = $this->tokenService->createPaymentToken($this->tokenPayload);
            return $paymentToken;
        }
    }

**VerifyPaymentTokenAPI**

    use com\checkout;
    class VerifyPaymentTokenAPI {
        private $apiClient;
        private $charge;

        function __construct($secretKey) {
            $this->apiClient = new checkout\ApiClient($secretKey);
            $this->charge = $this->apiClient->chargeService();
        }

        public function getCharge($paymentToken) {
            $chargeResponse = $this->charge->verifyCharge($paymentToken);
            return $chargeResponse;
        }
    }

**Usage**

    require_once 'classes/PaymentTokenAPI.php';
    require_once 'classes/VerifyPaymentTokenAPI.php';
    include 'checkout-php-library/autoload.php';

    use com\checkout;
    $paymentToken = new PaymentTokenAPI('sk_test_467c512a-0ec8-4b7f-9428-f4a8a1938e9c');
    $paymentToken->setInvestmentValue('1000');
    try {	
        $token = ($paymentToken->createPaymentToken())->getId();
    }catch (checkout\helpers\ApiHttpClientCustomException $e) {
        echo 'Caught exception Message: ',  $e->getErrorMessage(), "\n";
	echo 'Caught exception Error Code: ',  $e->getErrorCode(), "\n";
        echo 'Caught exception Event id: ',  $e->getEventId(), "\n";
    }

    $getCharge = new VerifyPaymentTokenAPI('sk_test_467c512a-0ec8-4b7f-9428-f4a8a1938e9c');
    try {	
        $charge = $getCharge->getCharge($token);
    }catch (checkout\helpers\ApiHttpClientCustomException $e) {
        echo 'Caught exception Message: ',  $e->getErrorMessage(), "\n";
        echo 'Caught exception Error Code: ',  $e->getErrorCode(), "\n";
        echo 'Caught exception Event id: ',  $e->getEventId(), "\n";
    }`

**Comment by santiago-delpuerto-cko** [comment]
Hi Carlbinalla, 

The Payment Token created from your backend is only valid for Alternative Payments as explained [here](https://docs.checkout.com/getting-started/checkout-js/complete-alt.-payment-charge)

If you want to create a Credit Card charge you can do it using a Card Token created via one of our JS solutions (Checkout.js or Frames) as explained [here](https://docs.checkout.com/getting-started/checkout-js/charge-via-card-token) and use it with the `chargeWithCardToken` method of the API.

In case the Card Charge is 3DS, you will get a new Token in the redirection back to success URL that you can use to Verify Payment and retrieve the payment details. More details [here](https://docs.checkout.com/getting-started/merchant-api/3d-secure-charges/3d-charge-with-card-token)

PCI-compliant merchants also have the option of Charging a Card with Full Card Details instead of Card Token.

If there is any further doubt do not hesitate to write us to integration@checkout.com. 

Kind Regards, 
Santiago.

**Comment by carlbinalla** [comment]
I am planning to use **Alternative Payments**. I sent a ticket to support@checkout.com, they said that it may be because the **Payment Token** that I am verifying is not linked to any transaction

**Comment by santiago-delpuerto-cko** [comment]
Hi carlbinalla, 

That's correct. The Payment Token generated from the backend should be used in **checkout.JS** at your frontend, as explained in step 2 in the following link: https://docs.checkout.com/getting-started/checkout-js/complete-alt.-payment-charge

Once payment is completed on the Alternative Payment gateway, the shopper will be redirected to your website. At your server end, you will obtain **a new** payment token via the form variable _cko-payment-token_, that you can verify in order to know the charge status. 

Kind regards, 
Santiago.
