### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by loranger** [checkout/checkout-php-library#83]
Hello,

I can't refund any transaction using the API.

Each time I try, using the charge_id I get back when I did charge, I have the following error
```
An error has occurred while processing your transaction
Transaction Not Found
```

Here is the code I use

```php
$chargeCapturePayload = new com\checkout\ApiServices\Charges\RequestModels\ChargeRefund();

$chargeCapturePayload->setChargeId( $this->transaction_id );
$chargeCapturePayload->setValue( $this->getProduct()->getPrice() );
try {
    $this->response = $charge->refundCardChargeRequest($chargeCapturePayload);
} catch (Exception $e) {
    return $this->fail($e);
}
```

My `transaction_id` is the charge_id (`charge_82DADA...`) I use in order to find and refund the payment manually in the hub.checkout.com

Everything else works flawlessly
What did I miss ?

**Comment by josian-castel-cko** [comment]
Dear Sir,

Hope you are doing fine.

Grateful if you could advise whether you are using the captured or the auth charge id to process the refund.

Please also provide us your test public key you are using on sandbox, same will help us identify your account.

Wishing you a nice day ahead.

Kind regards, 
Josian

**Comment by loranger** [comment]
Hello,

Thanks for your kind reply.

I use the charge_id the api returned when I initially charged the card:
```php
$response = $charge->chargeWithCard($cardChargePayload);
$transaction_id = $response->getID();
```
In my example, the payment whas captured on month ago.

My sandbox publishable key is the following: `pk_test_ff3b2323-c500-4bc2-9eaf-70a56fb4b5be`

Thank you for your support

**Comment by josian-castel-cko** [comment]
Dear Sir,

Please note that you need to use the captured charge id instead of the the auth charge id you get in the charge response.

To elaborate a little, note that auth only means the transaction was reserved on the customers card. It is only when you capture that charge that same is deducted from the customers card and credited to your companies account.

When sending a request, you have the option to either automatically capture the transactions by sending the autoCapture flag as Y (Yes). If same is set to N (No) the transaction will stay in authorize status for 7 days and unless same is captured either through API or using the HUB, same will be voided (amount released back to customers card) passed the 7th day.

Thus, if autoCapture is set to Y, the transaction will automatically be captured and to process a refund you need to use the captured charge id to process the refund.

Since, you will only get the auth charge id in the gateway charge response, you can use one for the 4 solution described below.

1. Webhook: Same is an automated notification triggered by a specific event. The Webhook notification will ensure that you get a notification for all status change (e.g auth to capture, or capture to refund). The documentation for Webhook can be accessed [here](http://docs.checkout.com/getting-started/webhooks)

2. Do a get charge history: This endpoint can be used to get all charge status related to a specific charge. You can refer to the documentation [here](http://docs.checkout.com/reference/merchant-api-reference/charges/get-charge-history).

3. Use our Reporting API solution: This solution will enable you to query transaction using specific filters e.g query using the auth charge id, customer email or query all captured transaction processed for a specific time range. Documentation available [here](http://docs.checkout.com/reference/merchant-api-reference/reporting/query-transaction). 

4. Do back to back auth capture: With this option, you need to set autoCapture flag as N and capture the auth transaction through API. When you send the request to capture the transaction, you will get the captured charge id in the response. To capture an auth transaction please refer [here](http://docs.checkout.com/reference/merchant-api-reference/charges/charge-actions/capture-card-charge). 

Hope the above helps, do let me know should you require any clarifications.

For any future integration related communications, please send an email to integration@checkout.com.
Myself or one of my colleagues will be happy to assist you.

Kind regards,
Josian

**Comment by loranger** [comment]
Thank you so much Josian !

I will try your second or third solution as it fits well in my actual workflow.

I close this issue and I hope it may help anyone having the same troubles as I had.

Thank you again

Regards,
Laurent

**Comment by ppshobi** [comment]
actually, those links are not working now

**Comment by nicolas-maalouf-cko** [comment]
@ppshobi please refer to our updated PHP SDK:
https://github.com/checkout/checkout-sdk-php
